### ISSUE TITLE
Little Bug

### ISSUE THREAD

**Issue by PrincipeSayan** [bateman/corsaronero-cp-provider#15]
Thank you both so much for the work you've done. I used your plugin for a few month and now I face this problem very often, I hope you can help me out:

Version of CouchPotato: source:(CouchPotato:CouchPotatoServer master) 711310d0 (2017-03-27 11:55:38)
Running on: FreeNAS-9.10.2-U1

### Logs:
```
04-21 17:50:40 ERROR [              corsaronero] Failed parsing ilCorsaroNero: Traceback (most recent call last):
  File "/var/db/couchpotato/custom_plugins/corsaronero/main.py", line 53, in _searchOnTitle
    self.parseResults(results, entries_1, movie, title)
  File "/var/db/couchpotato/custom_plugins/corsaronero/main.py", line 114, in parseResults
    new['url'] = self.getMagnetLink(new['detail_url'])
  File "/var/db/couchpotato/custom_plugins/corsaronero/main.py", line 76, in getMagnetLink
    magnet = html.find('a', attrs={'class': 'forbtn'})['href']
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by neothematrix** [comment]
thanks a lot, indeed there were some issues with some search results (corsaronero returned a correct download page but with a 302 redirect to the home page). I fixed by changing the way the plugin retrieves the download link, it was using a magnet link before, now it uses a torrent link, which now makes it also possible for people to use the "black hole" download method. In addition, we have one less http call for each search result, so it should be a huge performance improvement.
Please test the new commit and let me know if you have any issue!

**Comment by PrincipeSayan** [comment]
Sorry for the late answer. Good job ^^ Love this plugin.
I didn't do a deep test for your commit but it seems to work pretty well, no more errors! And torrent are transfering and downloading nicely. Thank you even for the perfomance improvement, always welcome.
